### ISSUE TITLE
how do I record system audio?

### ISSUE THREAD

**Issue by Barnac1ed** [xan105/node-video-capture#1]
after looking through my audio devices using ffmpeg, I either recorded the audio coming from my mic, or the audio from the video was muted.

thx in advance

**Comment by xan105** [comment]
To record your system's audio you need a loopback interface aka "what you hear" or "stereo mix".
It's often hidden and disabled by default and only some audio card have the option.

I'm using this lib in another project ([xan105/Achievement-Watcher](https://github.com/xan105/Achievement-Watcher)) to record user system audio (any audio card) I'm using "virtual-audio-capturer" : [rdp/virtual-audio-capture-grabber-device](https://github.com/rdp/virtual-audio-capture-grabber-device) from [rdp/screen-capture-recorder-to-video-windows-free](https://github.com/rdp/screen-capture-recorder-to-video-windows-free).

Not going into details but I never found a reliable way to sync video/audio with this tho. Hence the `audioDelay` option. A value around 700-900ms is fine most of the time.

_Usage example_
```js
import { hwencode } from "@xan105/video-capture";

hwencode("./path/to/file.mp4", "h264_nvenc", { 
  audioInterface: "virtual-audio-capturer" 
})
.then(console.log)
.catch(console.error);
```
